language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '10'
  - '9'
  - '8'

before_script:
  - npm run build

jobs:
  include:
    - stage: npm release
      if: branch = master AND type != pull_request
      node_js: "8"
      before_script:
        - npm run build
      script: npm run semantic-release
